# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fraise < Formula
  desc "In-memory temporal graph database for AI agents memory"
  homepage "https://github.com/FraiseHQ/fraise"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FraiseHQ/fraise/releases/download/v0.3.1/fraise_0.3.1_darwin_amd64.tar.gz"
      sha256 "f877f888e2443469e4af11a2ea81c71bf274894a6d934a41a74ac10e8cb5d9da"

      define_method(:install) do
        bin.install "fraise"
        (etc/"fraise").install "fraise.config.toml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FraiseHQ/fraise/releases/download/v0.3.1/fraise_0.3.1_darwin_arm64.tar.gz"
      sha256 "880990fb7f19c3adf008a22f57ae5b1b91174a97416c02ff55d5f4c532460a37"

      define_method(:install) do
        bin.install "fraise"
        (etc/"fraise").install "fraise.config.toml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FraiseHQ/fraise/releases/download/v0.3.1/fraise_0.3.1_linux_amd64.tar.gz"
      sha256 "520960cb20987b53df92879fdd9f396ef3e65a51f69af7a5b11dd3aeda71f10e"
      define_method(:install) do
        bin.install "fraise"
        (etc/"fraise").install "fraise.config.toml"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FraiseHQ/fraise/releases/download/v0.3.1/fraise_0.3.1_linux_arm64.tar.gz"
      sha256 "1641db7a63c62f321b5f93dbc0b9b6844e2a961cbd1c390ae48bcf4310368c66"
      define_method(:install) do
        bin.install "fraise"
        (etc/"fraise").install "fraise.config.toml"
      end
    end
  end

  def caveats
    <<~EOS
      Run fraise as a supervised background service:
        brew services start fraise
      Config:  #{etc}/fraise/fraise.config.toml
      Logs:    #{var}/log/fraise.log
    EOS
  end

  service do
    run [opt_bin/"fraise", "-config", etc/"fraise/fraise.config.toml"]
    keep_alive true
    log_path var/"log/fraise.log"
    error_log_path var/"log/fraise.log"
    working_dir var
  end

  test do
    assert_match "-config", shell_output("#{bin}/fraise -h 2>&1")
  end
end
