# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fraise < Formula
  desc "In-memory temporal graph database for AI agents memory"
  homepage "https://github.com/FraiseHQ/fraise"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FraiseHQ/fraise/releases/download/v0.3.2/fraise_0.3.2_darwin_amd64.tar.gz"
      sha256 "82da3b5eea58b2ca1d64200f25da783a1e05cdd25c07fd6759762c857f8fac7e"

      define_method(:install) do
        bin.install "fraise"
        (etc/"fraise").install "fraise.config.toml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FraiseHQ/fraise/releases/download/v0.3.2/fraise_0.3.2_darwin_arm64.tar.gz"
      sha256 "8f2e85ac32a599f4e25a8544a294f3d8995d33f5ce971e23144ed8ac23386793"

      define_method(:install) do
        bin.install "fraise"
        (etc/"fraise").install "fraise.config.toml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FraiseHQ/fraise/releases/download/v0.3.2/fraise_0.3.2_linux_amd64.tar.gz"
      sha256 "2c03435d4cdc585bb4d9d36743bfd5b4ec32e1cbf0999e2bcb35fbbe80112673"
      define_method(:install) do
        bin.install "fraise"
        (etc/"fraise").install "fraise.config.toml"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FraiseHQ/fraise/releases/download/v0.3.2/fraise_0.3.2_linux_arm64.tar.gz"
      sha256 "b52baecf2fb98537d7f2a9f61b65888d055fe2d895c27bfd29333fb46a53a2de"
      define_method(:install) do
        bin.install "fraise"
        (etc/"fraise").install "fraise.config.toml"
      end
    end
  end

  def caveats
    <<~EOS
      Run fraise as a supervised background service:
        brew services start fraise
      Config:  #{etc}/fraise/fraise.config.toml
      Logs:    #{var}/log/fraise.log
    EOS
  end

  service do
    run [opt_bin/"fraise", "-config", etc/"fraise/fraise.config.toml"]
    keep_alive true
    log_path var/"log/fraise.log"
    error_log_path var/"log/fraise.log"
    working_dir var
  end

  test do
    assert_match "-config", shell_output("#{bin}/fraise -h 2>&1")
  end
end
