# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fraise < Formula
  desc "In-memory temporal graph database for AI agents memory"
  homepage "https://github.com/FraiseHQ/fraise"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FraiseHQ/fraise/releases/download/v0.2.2/fraise_0.2.2_darwin_amd64.tar.gz"
      sha256 "9702169a266262f8172db585895ef16cb45239acf1f26cc0bbc4ed4654d22680"

      define_method(:install) do
        bin.install "fraise"
        (etc/"fraise").install "fraise.config.toml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FraiseHQ/fraise/releases/download/v0.2.2/fraise_0.2.2_darwin_arm64.tar.gz"
      sha256 "ec19f4f057bc0d1a490d28536e25e201cdeaa4b6d07663b7dd9fbd2dc466da26"

      define_method(:install) do
        bin.install "fraise"
        (etc/"fraise").install "fraise.config.toml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FraiseHQ/fraise/releases/download/v0.2.2/fraise_0.2.2_linux_amd64.tar.gz"
      sha256 "c32eb59e9df42a30f72863e01ecb8eafafc6ea477c6ff5d1b5edb9f5cf0b1a7b"
      define_method(:install) do
        bin.install "fraise"
        (etc/"fraise").install "fraise.config.toml"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FraiseHQ/fraise/releases/download/v0.2.2/fraise_0.2.2_linux_arm64.tar.gz"
      sha256 "7d211008eb55964d42adc78aecbf12f3452bb85e9c17d2c834abec35f6fc5375"
      define_method(:install) do
        bin.install "fraise"
        (etc/"fraise").install "fraise.config.toml"
      end
    end
  end

  def caveats
    <<~EOS
      Run fraise as a supervised background service:
        brew services start fraise
      Config:  #{etc}/fraise/fraise.config.toml
      Logs:    #{var}/log/fraise.log
    EOS
  end

  service do
    run [opt_bin/"fraise", "-config", etc/"fraise/fraise.config.toml"]
    keep_alive true
    log_path var/"log/fraise.log"
    error_log_path var/"log/fraise.log"
    working_dir var
  end

  test do
    assert_match "-config", shell_output("#{bin}/fraise -h 2>&1")
  end
end
